### ISSUE TITLE
[SolidLiquidSep] Initial-holdup snapshots break raw-material and OPEX reporting

### ISSUE THREAD

**Issue by sergey-gusev94** [PharmaPy-org/PharmaPy#311]
Both `DeliquoringStep.Phases` and `DisplacementWashing.Phases` store a dictionary in `__original_phase__`, while `SimulationExec.get_holdup` expects a phase or mixed-phase object. Default raw-material and OPEX reporting then fails with `AttributeError: 'dict' object has no attribute 'transferred_from_uo'`.

Severity: medium. Discovered during #263; pre-existing and reproduced on both `f7a99c8d83aeb8f09d519a96cc74b53c7e82c853` and baseline `c11abed89d4ce9da6c33c559f6ad05c393dd969a` using supplied `Cake` inputs. Related #76 concerns different raw-material/OPEX argument and basis defects. Stream tables encounter this failure before the independent pandas 3 incompatibility tracked in #327.

The [deliquoring setter](https://github.com/PharmaPy-org/PharmaPy/blob/f7a99c8d83aeb8f09d519a96cc74b53c7e82c853/PharmaPy/SolidLiquidSep.py#L428) and [washing setter](https://github.com/PharmaPy-org/PharmaPy/blob/f7a99c8d83aeb8f09d519a96cc74b53c7e82c853/PharmaPy/SolidLiquidSep.py#L1773) both assign:

```python
self.__original_phase__ = copy.deepcopy(self.Liquid_1.__dict__)
```

The [consumer](https://github.com/PharmaPy-org/PharmaPy/blob/f7a99c8d83aeb8f09d519a96cc74b53c7e82c853/PharmaPy/SimExec.py#L724-L738) accesses `phases.transferred_from_uo` and then extracts attributes from the phase object. [GetRawMaterials](https://github.com/PharmaPy-org/PharmaPy/blob/f7a99c8d83aeb8f09d519a96cc74b53c7e82c853/PharmaPy/SimExec.py#L741-L781) includes holdups by default, and `GetOPEX` uses that accounting. [GetStreamTable](https://github.com/PharmaPy-org/PharmaPy/blob/f7a99c8d83aeb8f09d519a96cc74b53c7e82c853/PharmaPy/Results.py#L309) also requests raw materials with default holdup inclusion.

Portable minimal reproduction: run from the checkout root using `.pixi/envs/assimulo/bin/python`, or save as `repro.py` and run `pixi run -e assimulo python repro.py`. The evidence environment was Python 3.11.15, NumPy 1.26.4, pandas 3.0.3, Assimulo 3.4.3. This diagnostic uses real phase/cake objects and public setters without running a solver. Supplying a `Cake` also avoids an independent baseline phase-list setter failure.

```python
# Run from the checkout being tested; guard against another editable install.
import sys as _sys
from pathlib import Path as _Path
_checkout = _Path.cwd().resolve()
_sys.path.insert(0, str(_checkout))
import PharmaPy as _PharmaPy
assert _Path(_PharmaPy.__file__).resolve().parent.parent == _checkout

import PharmaPy
print("package", PharmaPy.__file__)
import numpy as np
from PharmaPy.SimExec import SimulationExec
from PharmaPy.Phases import LiquidPhase, SolidPhase
from PharmaPy.MixedPhases import Cake
from PharmaPy.SolidLiquidSep import DeliquoringStep, DisplacementWashing

path = "tests/Flowsheet/data/compound_database.json"
sim = SimulationExec(path, flowsheet="DL01 --> W01")
for unit_type in (DeliquoringStep, DisplacementWashing):
    # Synthetic directly charged cake, with 0.1 L of liquid at 300 K.
    liquid = LiquidPhase(path, temp=300., mass_frac=[.1, .1, .1, .1, .6],
                         vol=1e-4)  # [K], [-], [m**3]
    solid = SolidPhase(path, x_distrib=np.array([100., 200., 300.]),
                       distrib=np.array([1e4, 2e4, 1e4]),
                       mass_frac=[0, 0, 1, 0, 0], kv=1.)
    # Above: diameter [um], number distribution [#/um], fractions and kv [-].
    cake = Cake(num_discr=5)  # five spatial nodes suffice to test the setter
    cake.Phases = [liquid, solid]
    options = {"solvent_idx": 4} if unit_type is DisplacementWashing else {}
    unit = unit_type(num_nodes=5, diam_unit=.1, **options)  # diameter [m]
    unit.Phases = cake
    print(unit_type.__name__, type(unit.__original_phase__).__name__)
    for basis in ("mass", "mole"):
        try:
            sim.get_holdup(unit, basis=basis)
        except AttributeError as error:
            print(basis, type(error).__name__, str(error))
```

Observed for each unit, on both tested trees:

```text
dict
mass AttributeError 'dict' object has no attribute 'transferred_from_uo'
mole AttributeError 'dict' object has no attribute 'transferred_from_uo'
```

The complete branch flowsheet `BatchReactor -> BatchCryst -> Filter -> DeliquoringStep -> DisplacementWashing` also finished with real CVode integration, then reproduced this error in both default `GetRawMaterials` bases and `GetOPEX`. The three-unit control without deliquoring/washing completed its accounting. That full five-unit baseline flow fails earlier in washing phase update, so the baseline age claim rests on the supplied-Cake reproduction, not on a claimed successful baseline five-unit solve.

For a transferred cake, the dictionary already contains `transferred_from_uo=True`; reporting should omit a duplicate charge and retain the flowsheet's legitimate initial charges. For direct charge, the stored liquid snapshot represents a real inventory (about `0.09331942 kg` in this fixture). The attached solid inventory must also be considered when defining complete direct-charge cake accounting: changing the snapshot to a liquid object only establishes a type repair, not complete two-phase inventory accounting.

`include_holdups=False` avoids the crash for raw materials/OPEX but drops all initial holdups, including unrelated valid charges. It is a lossy workaround. `GetStreamTable` exposes no such option and still needs #327 after this repair.

Acceptance criteria:

- Make these units' snapshots compatible with the existing holdup consumer and preserve initial state independently of later phase updates. Define whether the charged inventory includes both phases, rather than assuming a liquid-only snapshot is complete.
- Test both units with transferred and directly charged cakes, checking mass [kg], amount [mol], species ordering, and phase contributions. Transferred cakes must not be counted twice; other units' initial holdups must remain present.
- Exercise `GetRawMaterials` and `GetOPEX` through the public flowsheet path, including both mass and mole reporting. Test object values and inventories, not only absence of an exception.
- Keep the pandas 3 stream-table blocker separately tracked in #327; resolving this type mismatch alone does not restore that API.

**Comment by bernalde** [comment]
The downstream pandas 3 grouping failure in #327 now has a focused implementation in PR #334, with real batch/continuous Mixer stream-table regressions on both material bases. It does not change the deliquoring/washing snapshots or the initial-holdup consumer. This issue remains open and still owns complete direct-charge versus transferred-cake accounting and the public raw-material/OPEX handoff. After its fix, retain coverage through `GetStreamTable` as well; the separate grouping fix is traceable in #334.
